source 'https://rubygems.org'


gem 'rails', '4.2.5.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'devise-i18n'
gem 'mysql'
gem 'bootstrap-sass'
gem 'bootstrap'
gem 'bootstrap-tagsinput-rails'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
gem 'acts-as-taggable-on'
gem 'bcrypt'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :test do
	gem 'capybara', '2.6.2'
	gem 'factory_girl_rails', '~> 4.0'
end

group :test, :development do
  gem "rspec-rails", "3.4.2"
  gem "launchy"
  gem 'byebug'
end


