development:
  adapter: mysql
  encoding: utf8
  database: dbtoduni_development
  username: root
  password: 230296
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql
  encoding: utf8
  database: dbtoduni_test
  username: root
  password: 230296
  host: 127.0.0.1
  port: 3306
